# Generated by Django 5.0 on 2025-09-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
    ]
